name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

permissions:
  statuses: write 

jobs:
  develop-source-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch
        id: check_source_branch  
        timeout-minutes: 1
        run: |
          if [[ "${{ github.base_ref }}" != "develop" ]]; then
            echo "This action only runs on pull requests targeting the 'develop' branch."
            exit 0  
          elif [[ ! "${{ github.head_ref }}" =~ ^feature/[a-z0-9]+-ENG-[0-9]{5}-.*$ ]]; then
            echo "::error::Pull requests to 'develop' must originate from branches named 'feature/[a-z0-9]+-ENG-#####-*'."
            exit 1  
          else
            echo "Branch name check passed"
          fi

      - name: Update PR Status
        if: always() 
        uses: actions/github-script@v6
        with:
          script: |
            const branchCheckResult = '${{ steps.check_source_branch.outcome }}';
            const state = branchCheckResult === 'success' ? 'success' : 'failure';
            const description = `Branch name check ${state}.`;

            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha: context.payload.pull_request.head.sha,
              state,
              context: "develop-source-branch-check", 
              description,
            });

