name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

permissions:
  statuses: write

jobs:
  develop-source-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Source Branch Starts with 'feature/'
        if: "!startsWith(github.head_ref, 'feature/')"  # Condition for failure
        run: |
          echo "::error::Pull requests to 'develop' must originate from branches starting with 'feature/'."
          exit 1

      - name: Update PR Status (Success)
        if: always() && github.base_ref == 'develop'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              ...context.repo,
              sha: context.payload.pull_request.head.sha,
              state: "success",
              context: "Branch Protection",
              description: "Branch name check passed"
            });
