name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]

permissions:
  statuses: write

jobs:
  develop-source-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Source Branch Starts with 'feature/'
        id: branch-check
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^feature/ ]]; then
            echo "::error::Pull requests to 'develop' must originate from branches starting with 'feature/'."
            echo "status=failure" >> $GITHUB_ENV
            exit 1
          else
            echo "status=success" >> $GITHUB_ENV
          fi

      - name: Update PR Status (Success/Failure)
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = process.env.status;
            github.rest.repos.createCommitStatus({
              ...context.repo,
              sha: context.payload.pull_request.head.sha,
              state: status,
              context: "Branch Protection",
              description: status === "success" ? "Branch name check passed" : "Branch name check failed"
            });